spring:
 datasource:
   url: jdbc:mysql://localhost:3306/user?useSSL=false&serverTimezone=UTC
   username: 
   password: 
 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
 data:
   redis:
     host: localhost
     port: 6379

    url: jdbc:mysql://localhost:3306/user?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
